name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./client
      - name: Run tests
        run: yarn test 
        working-directory: ./client
        env:
          CI: 'true'

  server:
    name: Server
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15.1
      - name: Run tests
        run: go test ./... -args ci
        working-directory: ./server
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
